import {
  Student,
  Teacher,
  Course,
  Batch,
  LiveClass,
  StudyMaterial,
  Assignment,
  QuestionBankItem,
  MockExam,
  EnquiryLead,
  AuditLog,
} from './types/admin';

export const mockStudents: Student[] = [
  {
    id: 'std_01',
    name: 'Aarav Sharma',
    rollNo: 'OCI-2026-849',
    email: 'aarav.sharma@gmail.com',
    phone: '+91 98765 43210',
    courseId: 'crs_01',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    batchId: 'batch_alpha',
    batchName: 'JEE Alpha Super 30',
    admissionDate: '2026-04-10',
    status: 'active',
    avgMockScore: 248,
  },
  {
    id: 'std_02',
    name: 'Ananya Roy',
    rollNo: 'OCI-2026-850',
    email: 'ananya.roy@gmail.com',
    phone: '+91 98765 43211',
    courseId: 'crs_01',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    batchId: 'batch_alpha',
    batchName: 'JEE Alpha Super 30',
    admissionDate: '2026-04-12',
    status: 'active',
    avgMockScore: 262,
  },
  {
    id: 'std_03',
    name: 'Devansh Gupta',
    rollNo: 'OCI-2026-851',
    email: 'devansh.g@gmail.com',
    phone: '+91 98765 43212',
    courseId: 'crs_01',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    batchId: 'batch_beta',
    batchName: 'JEE Beta Batch',
    admissionDate: '2026-04-15',
    status: 'active',
    avgMockScore: 172,
  },
  {
    id: 'std_04',
    name: 'Ishita Sen',
    rollNo: 'OCI-2026-852',
    email: 'ishita.sen@gmail.com',
    phone: '+91 98765 43213',
    courseId: 'crs_02',
    courseName: 'NEET UG Medical Pinnacle',
    batchId: 'batch_neet_01',
    batchName: 'NEET Achievers 2027',
    admissionDate: '2026-04-20',
    status: 'active',
    avgMockScore: 610,
  },
  {
    id: 'std_05',
    name: 'Kabir Patel',
    rollNo: 'OCI-2026-853',
    email: 'kabir.patel@gmail.com',
    phone: '+91 98765 43214',
    courseId: 'crs_03',
    courseName: 'Foundation Class 11th Olympiad',
    batchId: 'batch_fnd_01',
    batchName: 'Foundation Alpha',
    admissionDate: '2026-05-01',
    status: 'active',
    avgMockScore: 185,
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: 'tch_01',
    name: 'Dr. H. C. Verma',
    employeeId: 'FAC-PHY-102',
    email: 'dr.verma@oci-institute.edu',
    phone: '+91 98123 45678',
    subject: 'Physics',
    qualification: 'Ph.D in Physics, Ex-IIT Faculty',
    experienceYears: 24,
    assignedBatches: ['JEE Alpha Super 30', 'JEE Beta Batch'],
    status: 'active',
    activeLiveClassesToday: 2,
    bio: 'Renowned author and mentor with 24+ years experience training Top 100 AIR rankers in JEE Advanced.',
  },
  {
    id: 'tch_02',
    name: 'Dr. O. P. Tandon',
    employeeId: 'FAC-CHM-104',
    email: 'dr.tandon@oci-institute.edu',
    phone: '+91 98123 45679',
    subject: 'Chemistry',
    qualification: 'Ph.D in Organic Chemistry',
    experienceYears: 20,
    assignedBatches: ['JEE Alpha Super 30', 'NEET Achievers 2027'],
    status: 'active',
    activeLiveClassesToday: 1,
    bio: 'Specialist in reaction mechanisms, chemical kinetics, and stereochemistry with deep exam insights.',
  },
  {
    id: 'tch_03',
    name: 'Prof. Amit M. Agarwal',
    employeeId: 'FAC-MAT-108',
    email: 'prof.agarwal@oci-institute.edu',
    phone: '+91 98123 45680',
    subject: 'Mathematics',
    qualification: 'M.Sc Mathematics, Gold Medalist',
    experienceYears: 16,
    assignedBatches: ['JEE Alpha Super 30', 'Foundation Alpha'],
    status: 'active',
    activeLiveClassesToday: 2,
    bio: 'Pioneer of shortcut visualization methods for Calculus, Coordinate Geometry, and Vectors.',
  },
  {
    id: 'tch_04',
    name: 'Dr. Neela Bakore',
    employeeId: 'FAC-BIO-112',
    email: 'dr.bakore@oci-institute.edu',
    phone: '+91 98123 45681',
    subject: 'Biology',
    qualification: 'M.D. & Senior Botanist',
    experienceYears: 18,
    assignedBatches: ['NEET Achievers 2027'],
    status: 'active',
    activeLiveClassesToday: 1,
    bio: 'Empowers medical aspirants with conceptual mastery of Botany and Human Physiology.',
  },
];



export const mockCourses: Course[] = [
  {
    id: 'crs_01',
    name: 'JEE Advanced 2 Year Comprehensive',
    code: 'JEE-ADV-2Y',
    category: 'Engineering (JEE)',
    durationMonths: 24,
    description: 'Premier coaching program for JEE Main & Advanced with intensive mock drills and test series.',
    isActive: true,
    batchesCount: 3,
    enrolledStudentsCount: 180,
  },
  {
    id: 'crs_02',
    name: 'NEET UG Medical Pinnacle',
    code: 'NEET-UG-2Y',
    category: 'Medical (NEET)',
    durationMonths: 24,
    description: 'Rigorous NCERT-aligned medical prep covering Physics, Chemistry, Botany, and Zoology.',
    isActive: true,
    batchesCount: 2,
    enrolledStudentsCount: 140,
  },
  {
    id: 'crs_03',
    name: 'Foundation Class 11th Olympiad',
    code: 'FND-11',
    category: 'Foundation',
    durationMonths: 12,
    description: 'Strong base building for NTSE, KVPY, and early competitive exam preparation.',
    isActive: true,
    batchesCount: 1,
    enrolledStudentsCount: 100,
  },
];

export const mockBatches: Batch[] = [
  {
    id: 'batch_alpha',
    name: 'JEE Alpha Super 30',
    courseId: 'crs_01',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    teacherId: 'tch_01',
    teacherName: 'Dr. H. C. Verma',
    schedule: 'Mon, Wed, Fri (10:00 AM - 01:30 PM)',
    roomName: 'Lecture Hall A & Virtual Room 1',
    startDate: '2026-04-15',
    endDate: '2027-03-31',
    capacity: 45,
    enrolledCount: 42,
    status: 'ongoing',
  },
  {
    id: 'batch_beta',
    name: 'JEE Beta Batch',
    courseId: 'crs_01',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    teacherId: 'tch_01',
    teacherName: 'Dr. H. C. Verma',
    schedule: 'Tue, Thu, Sat (02:00 PM - 05:30 PM)',
    roomName: 'Lecture Hall B & Virtual Room 2',
    startDate: '2026-04-15',
    endDate: '2027-03-31',
    capacity: 60,
    enrolledCount: 55,
    status: 'ongoing',
  },
  {
    id: 'batch_neet_01',
    name: 'NEET Achievers 2027',
    courseId: 'crs_02',
    courseName: 'NEET UG Medical Pinnacle',
    teacherId: 'tch_04',
    teacherName: 'Dr. Neela Bakore',
    schedule: 'Daily (09:00 AM - 01:00 PM)',
    roomName: 'BioLab Hall 1',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    capacity: 50,
    enrolledCount: 48,
    status: 'ongoing',
  },
];

export const mockLiveClasses: LiveClass[] = [
  {
    id: 'cls_101',
    title: 'Physics: Electrostatics Lecture 4 (Gauss Law)',
    subject: 'Physics',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    batchId: 'batch_alpha',
    batchName: 'JEE Alpha Super 30',
    teacherId: 'tch_01',
    teacherName: 'Dr. H. C. Verma',
    scheduledStartTime: '2026-08-11T10:00:00+05:30',
    scheduledEndTime: '2026-08-11T11:30:00+05:30',
    jitsiRoomName: 'OCI_ROOM_PHYSICS_CLS101',
    status: 'live',
    attendeeCount: 42,
  },
  {
    id: 'cls_102',
    title: 'Chemistry: Chemical Equilibrium & Reaction Quotient',
    subject: 'Chemistry',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    batchId: 'batch_alpha',
    batchName: 'JEE Alpha Super 30',
    teacherId: 'tch_02',
    teacherName: 'Dr. O. P. Tandon',
    scheduledStartTime: '2026-08-11T14:00:00+05:30',
    scheduledEndTime: '2026-08-11T15:30:00+05:30',
    jitsiRoomName: 'OCI_ROOM_CHEM_CLS102',
    status: 'scheduled',
  },
  {
    id: 'cls_103',
    title: 'Botany: Plant Kingdom & Photosynthesis Pigments',
    subject: 'Biology',
    courseName: 'NEET UG Medical Pinnacle',
    batchId: 'batch_neet_01',
    batchName: 'NEET Achievers 2027',
    teacherId: 'tch_04',
    teacherName: 'Dr. Neela Bakore',
    scheduledStartTime: '2026-08-11T16:00:00+05:30',
    scheduledEndTime: '2026-08-11T17:30:00+05:30',
    jitsiRoomName: 'OCI_ROOM_BIO_CLS103',
    status: 'scheduled',
  },
];

export const mockEnquiries: EnquiryLead[] = [
  {
    id: 'enq_01',
    name: 'Siddharth Mohanty',
    phone: '+91 94370 12345',
    email: 'sid.mohanty@gmail.com',
    interestedCourse: 'JEE Advanced 2 Year Comprehensive',
    message: 'Interested in admissions for Class 11th JEE Batch. Want to inquire about scholarship test dates.',
    source: 'Website Form',
    status: 'NEW',
    createdAt: '2026-08-11T09:30:00+05:30',
  },
  {
    id: 'enq_02',
    name: 'Priyanka Dash',
    phone: '+91 94370 98765',
    email: 'priyanka.dash@gmail.com',
    interestedCourse: 'NEET UG Medical Pinnacle',
    message: 'Requesting syllabus brochure and batch schedule breakdown for NEET 2027 batch.',
    source: 'Mobile App',
    status: 'CONTACTED',
    createdAt: '2026-08-10T14:15:00+05:30',
    notes: 'Called on 10 Aug. Parent requested center visit this Saturday.',
  },
  {
    id: 'enq_03',
    name: 'Alok Tripathy',
    phone: '+91 98610 55443',
    email: 'alok.tripathy@yahoo.com',
    interestedCourse: 'Foundation Class 11th Olympiad',
    message: 'Seeking demo lecture access for Physics with Dr. H. C. Verma.',
    source: 'WhatsApp',
    status: 'CONVERTED',
    createdAt: '2026-08-08T11:00:00+05:30',
    notes: 'Enrolled under Roll OCI-2026-854.',
  },
];

export const mockQuestions: QuestionBankItem[] = [
  {
    id: 'q_01',
    subject: 'Physics',
    topic: 'Electrostatics & Coulomb Law',
    difficulty: 'Medium',
    question: 'A point charge +q is placed at a distance d from an infinite grounded conducting plane. What is the electrostatic force on the charge?',
    options: [
      'q² / (16πε₀d²)',
      'q² / (4πε₀d²)',
      'Zero',
      'q² / (8πε₀d²)',
    ],
    correctOptionIndex: 0,
    explanation: 'Using the method of electrical images, an image charge -q is located at distance 2d from +q. Force F = q² / [4πε₀(2d)²] = q² / (16πε₀d²).',
    marks: 4,
    negativeMarks: 1,
  },
  {
    id: 'q_02',
    subject: 'Chemistry',
    topic: 'Chemical Equilibrium',
    difficulty: 'Easy',
    question: 'For the exothermic reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the equilibrium yield of NH₃ increases with:',
    options: [
      'Increasing temperature and decreasing pressure',
      'Decreasing temperature and increasing pressure',
      'Increasing temperature and increasing pressure',
      'Decreasing temperature and decreasing pressure',
    ],
    correctOptionIndex: 1,
    explanation: 'According to Le Chatelier’s principle, lowering temperature favors the exothermic forward reaction, and increasing pressure shifts equilibrium towards fewer moles of gas.',
    marks: 4,
    negativeMarks: 1,
  },
];

export const mockExams: MockExam[] = [
  {
    id: 'mock_04',
    title: 'All India JEE Advanced Full Mock #4',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    durationMinutes: 180,
    totalMarks: 300,
    totalQuestions: 75,
    scheduledDate: '2026-08-11T09:00:00+05:30',
    isPublished: true,
    attemptCount: 380,
    avgScore: 218,
  },
  {
    id: 'mock_05',
    title: 'Physics & Chemistry Combined Unit Test',
    courseName: 'JEE Advanced 2 Year Comprehensive',
    durationMinutes: 90,
    totalMarks: 150,
    totalQuestions: 40,
    scheduledDate: '2026-08-18T10:00:00+05:30',
    isPublished: false,
    attemptCount: 0,
    avgScore: 0,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log_01',
    adminName: 'Prof. R. K. Agrawal',
    action: 'CREATE_BATCH',
    entityType: 'BATCH',
    entityId: 'batch_alpha',
    details: 'Configured and activated batch JEE Alpha Super 30',
    ipAddress: '103.24.12.8',
    timestamp: '2026-08-11T10:16:00+05:30',
  },
  {
    id: 'log_02',
    adminName: 'Prof. R. K. Agrawal',
    action: 'PUBLISH_MOCK_EXAM',
    entityType: 'EXAM',
    entityId: 'mock_04',
    details: 'Published All India JEE Mock 4 to 420 active enrolled students',
    ipAddress: '103.24.12.8',
    timestamp: '2026-08-11T08:30:00+05:30',
  },
];
